import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "sonner";
import "../style/globals.css";
import { AuthProvider } from "@/hooks/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventify",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <AuthProvider>
            {children}
            <Toaster position="bottom-right" richColors expand={false} />
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
